### ISSUE TITLE
Exception in constructor FrameLib_ProcessingQueue

### ISSUE THREAD

**Issue by flutomax** [AlexHarker/HISSTools_Freeze#4]
Hello! Im catch exception in constructor FrameLib_ProcessingQueue::FrameLib_ProcessingQueue.
Visual Studio 2019, Windows 10.
Detiles:
```
Exception thrown at 0x00007FFEA0FAB1AB in FL64.exe: 0xC0000005: 
Access violation executing location 0x00007FFEA0FAB1AB. occurred
```
Call stack:
```
>	00007ffea0fab1ab()	Unknown
 	user32.dll!00007fff0d30f1ce()	Unknown
 	user32.dll!00007fff0d30e1db()	Unknown
 	_FLEngine_x64.dll!0000000002e83b08()	Unknown
 	_FLEngine_x64.dll!0000000002e83b78()	Unknown
 	_FLEngine_x64.dll!0000000002e7ceda()	Unknown
 	_FLEngine_x64.dll!0000000002e27204()	Unknown
 	_FLEngine_x64.dll!0000000002dd1e46()	Unknown
 	_FLEngine_x64.dll!0000000002dd0d87()	Unknown
 	_FLEngine_x64.dll!000000000351148f()	Unknown
 	_FLEngine_x64.dll!0000000003573ad7()	Unknown
 	Fruity Wrapper_x64.dll!000000000b0accba()	Unknown
 	Fruity Wrapper_x64.dll!000000000b0a6886()	Unknown
 	_FLEngine_x64.dll!00000000030bf731()	Unknown
 	_FLEngine_x64.dll!00000000030e7dc9()	Unknown
 	_FLEngine_x64.dll!00000000030ea198()	Unknown
 	_FLEngine_x64.dll!0000000003510774()	Unknown
 	_FLEngine_x64.dll!0000000003516fea()	Unknown
 	_FLEngine_x64.dll!00000000030ef05a()	Unknown
 	_FLEngine_x64.dll!00000000034b4589()	Unknown
 	_FLEngine_x64.dll!00000000029ff7b1()	Unknown
 	_FLEngine_x64.dll!0000000002b87026()	Unknown
 	_FLEngine_x64.dll!0000000002b8df79()	Unknown
 	_FLEngine_x64.dll!0000000002e76540()	Unknown
 	_FLEngine_x64.dll!00000000033e9a9c()	Unknown
 	_FLEngine_x64.dll!0000000002b8d2fc()	Unknown
 	_FLEngine_x64.dll!0000000002afaef6()	Unknown
 	user32.dll!00007fff0d30e858()	Unknown
 	user32.dll!00007fff0d30e299()	Unknown
 	_FLEngine_x64.dll!0000000002e83b08()	Unknown
 	_FLEngine_x64.dll!0000000002e83b78()	Unknown
 	_FLEngine_x64.dll!0000000002e84068()	Unknown
 	_FLEngine_x64.dll!00000000035b1c31()	Unknown
 	FLEngine_x64.dll!00007ffea2268553()	Unknown
 	FL64.exe!00007ff7e9a33ba7()	Unknown
 	FL64.exe!00007ff7e9a33fcb()	Unknown
 	FL64.exe!00007ff7e9a35247()	Unknown
 	kernel32.dll!00007fff0ca37034()	Unknown
 	ntdll.dll!00007fff0dc826a1()	Unknown
```

**Comment by AlexHarker** [comment]
This might be to do with how framelib has been built. What hardware (CPU) are you running on?

@fearn-e - can you reproduce on your windows machine? It would be helpful to know, as if not it would point to this being a compiler flag issue.

**Comment by AlexHarker** [comment]
I've just checked and I suspect you are on a CPU without AVX (used for the framelib build)

I can turn that off later when I'm back at a computer. You could try building framelib with this off if you know how to do this in visual studio for both relevant projects. @flutomax

**Comment by AlexHarker** [comment]
@flutomax - please let me know if this release fixes your issue:

https://github.com/AlexHarker/HISSTools_Freeze/releases/tag/v1.0.1-sse

**Comment by flutomax** [comment]
> This might be to do with how framelib has been built. What hardware (CPU) are you running on?

Intel(R) Pentium(R) CPU  N3710  @ 1.60 GHz

**Comment by flutomax** [comment]
> @flutomax - please let me know if this release fixes your issue:
> 
> https://github.com/AlexHarker/HISSTools_Freeze/releases/tag/v1.0.1-sse

Thank you! Now all plugins are working well. However, I would like to assemble the plugin myself in order to thoroughly learn the principle of operation.

**Comment by AlexHarker** [comment]
No problem. The only change I made was to the framelib config. I compile framelib using the SSE branch, which has the relevant changes.

Let me know if you have any problems
